name: CI - CESIZen

on:
  push:      
    branches: [ main, staging ]
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests
        run: npm test -- --run

      - name: Build de l’application
        run: npm run build